model_name: autoencoder
batch_size: 16
max_epoch: 100
learning_rate: 5.0e-05
max_grad_norm: 10
fp16: false
num_workers: 0
pin_memory: true
in_channels: 3
out_channels: 3
z_channels: 4
channels: 64
n_res_blocks: 2
channel_multipliers:
- 1
- 2
- 4
- 4
emb_channels: 4
disc_start: 50001
kl_weight: 1.0e-06
disc_weight: 0.5
