model_name: chd_8bar
batch_size: 128
max_epoch: 1000
learning_rate: 0.001
max_grad_norm: 10
fp16: true
tfr_chd:
- 0.5
- 0
num_workers: 4
pin_memory: true
chd_n_step: 32
chd_input_dim: 36
chd_z_input_dim: 512
chd_hidden_dim: 512
chd_z_dim: 512
